import type { NutritionReference } from '@/types/nutrition';

export const mockNutritionDatabase: Record<string, NutritionReference> = {
  bread: {
    name: 'Bread',
    baseQuantity: 1,
    baseUnit: 'slice',
    calories: 82,
    protein: 3.2,
    carbs: 14.4,
    fat: 1.1,
    fiber: 2,
    sugar: 1.6,
    sodium: 145,
  },
  'peanut butter': {
    name: 'Peanut butter',
    baseQuantity: 15,
    baseUnit: 'gram',
    calories: 89,
    protein: 3.8,
    carbs: 3.2,
    fat: 7.5,
    fiber: 1.2,
    sugar: 1.4,
    sodium: 72,
  },
  'semi-skimmed milk': {
    name: 'Semi-skimmed milk',
    baseQuantity: 100,
    baseUnit: 'ml',
    calories: 46,
    protein: 3.4,
    carbs: 4.9,
    fat: 1.5,
    fiber: 0,
    sugar: 4.9,
    sodium: 44,
  },
  'skim milk': {
    name: 'Skim milk',
    baseQuantity: 100,
    baseUnit: 'ml',
    calories: 34,
    protein: 3.4,
    carbs: 5,
    fat: 0.1,
    fiber: 0,
    sugar: 5,
    sodium: 43,
  },
  yogurt: {
    name: 'Yogurt',
    baseQuantity: 100,
    baseUnit: 'gram',
    calories: 63,
    protein: 5.3,
    carbs: 7,
    fat: 1.5,
    fiber: 0,
    sugar: 6.8,
    sodium: 50,
  },
  'greek yogurt': {
    name: 'Greek yogurt',
    baseQuantity: 100,
    baseUnit: 'gram',
    calories: 97,
    protein: 8.8,
    carbs: 3.9,
    fat: 4.8,
    fiber: 0,
    sugar: 3.6,
    sodium: 36,
  },
  quark: {
    name: 'Quark',
    baseQuantity: 100,
    baseUnit: 'gram',
    calories: 67,
    protein: 11.5,
    carbs: 3.9,
    fat: 0.2,
    fiber: 0,
    sugar: 3.9,
    sodium: 45,
  },
  'cottage cheese': {
    name: 'Cottage cheese',
    baseQuantity: 100,
    baseUnit: 'gram',
    calories: 98,
    protein: 11.1,
    carbs: 3.4,
    fat: 4.3,
    fiber: 0,
    sugar: 2.7,
    sodium: 364,
  },
  'black coffee': {
    name: 'Black coffee',
    baseQuantity: 100,
    baseUnit: 'ml',
    calories: 2,
    protein: 0.1,
    carbs: 0,
    fat: 0,
    fiber: 0,
    sugar: 0,
    sodium: 2,
  },
  'coffee with milk': {
    name: 'Coffee with milk',
    baseQuantity: 100,
    baseUnit: 'ml',
    calories: 27,
    protein: 1.4,
    carbs: 2.6,
    fat: 1.2,
    fiber: 0,
    sugar: 2.6,
    sodium: 24,
  },
  tea: {
    name: 'Tea',
    baseQuantity: 100,
    baseUnit: 'ml',
    calories: 1,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
    sugar: 0,
    sodium: 2,
  },
  water: {
    name: 'Water',
    baseQuantity: 100,
    baseUnit: 'ml',
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
    sugar: 0,
    sodium: 0,
  },
  'orange juice': {
    name: 'Orange juice',
    baseQuantity: 100,
    baseUnit: 'ml',
    calories: 45,
    protein: 0.7,
    carbs: 10.4,
    fat: 0.2,
    fiber: 0.2,
    sugar: 8.4,
    sodium: 1,
  },
  cola: {
    name: 'Cola',
    baseQuantity: 100,
    baseUnit: 'ml',
    calories: 42,
    protein: 0,
    carbs: 10.6,
    fat: 0,
    fiber: 0,
    sugar: 10.6,
    sodium: 4,
  },
  'cola zero': {
    name: 'Cola zero',
    baseQuantity: 100,
    baseUnit: 'ml',
    calories: 1,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
    sugar: 0,
    sodium: 8,
  },
  'chocolate milk': {
    name: 'Chocolate milk',
    baseQuantity: 100,
    baseUnit: 'ml',
    calories: 77,
    protein: 3.4,
    carbs: 12.5,
    fat: 1.6,
    fiber: 0.3,
    sugar: 12.3,
    sodium: 55,
  },
  'chicken sandwich': {
    name: 'Chicken sandwich',
    baseQuantity: 1,
    baseUnit: 'serving',
    calories: 365,
    protein: 30,
    carbs: 33,
    fat: 11,
    fiber: 4,
    sugar: 5,
    sodium: 620,
  },
  apple: {
    name: 'Apple',
    baseQuantity: 1,
    baseUnit: 'piece',
    calories: 95,
    protein: 0.5,
    carbs: 25,
    fat: 0.3,
    fiber: 4.4,
    sugar: 19,
    sodium: 2,
  },
  banana: {
    name: 'Banana',
    baseQuantity: 1,
    baseUnit: 'piece',
    calories: 105,
    protein: 1.3,
    carbs: 27,
    fat: 0.4,
    fiber: 3.1,
    sugar: 14,
    sodium: 1,
  },
  orange: {
    name: 'Orange',
    baseQuantity: 1,
    baseUnit: 'piece',
    calories: 62,
    protein: 1.2,
    carbs: 15.4,
    fat: 0.2,
    fiber: 3.1,
    sugar: 12.2,
    sodium: 0,
  },
  blueberries: {
    name: 'Blueberries',
    baseQuantity: 100,
    baseUnit: 'gram',
    calories: 57,
    protein: 0.7,
    carbs: 14.5,
    fat: 0.3,
    fiber: 2.4,
    sugar: 10,
    sodium: 1,
  },
  strawberries: {
    name: 'Strawberries',
    baseQuantity: 100,
    baseUnit: 'gram',
    calories: 32,
    protein: 0.7,
    carbs: 7.7,
    fat: 0.3,
    fiber: 2,
    sugar: 4.9,
    sodium: 1,
  },
  rice: {
    name: 'Rice',
    baseQuantity: 100,
    baseUnit: 'gram',
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
    fiber: 0.4,
    sugar: 0.1,
    sodium: 1,
  },
  'brown rice': {
    name: 'Brown rice',
    baseQuantity: 100,
    baseUnit: 'gram',
    calories: 123,
    protein: 2.7,
    carbs: 25.6,
    fat: 1,
    fiber: 1.6,
    sugar: 0.4,
    sodium: 4,
  },
  potatoes: {
    name: 'Potatoes',
    baseQuantity: 100,
    baseUnit: 'gram',
    calories: 77,
    protein: 2,
    carbs: 17,
    fat: 0.1,
    fiber: 2.2,
    sugar: 0.8,
    sodium: 6,
  },
  'sweet potato': {
    name: 'Sweet potato',
    baseQuantity: 100,
    baseUnit: 'gram',
    calories: 86,
    protein: 1.6,
    carbs: 20.1,
    fat: 0.1,
    fiber: 3,
    sugar: 4.2,
    sodium: 55,
  },
  'chicken breast': {
    name: 'Chicken breast',
    baseQuantity: 100,
    baseUnit: 'gram',
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    sugar: 0,
    sodium: 74,
  },
  'turkey slices': {
    name: 'Turkey slices',
    baseQuantity: 100,
    baseUnit: 'gram',
    calories: 112,
    protein: 17,
    carbs: 2,
    fat: 3,
    fiber: 0,
    sugar: 1,
    sodium: 950,
  },
  ham: {
    name: 'Ham',
    baseQuantity: 100,
    baseUnit: 'gram',
    calories: 145,
    protein: 21,
    carbs: 1.5,
    fat: 5.5,
    fiber: 0,
    sugar: 1,
    sodium: 1200,
  },
  tuna: {
    name: 'Tuna',
    baseQuantity: 100,
    baseUnit: 'gram',
    calories: 116,
    protein: 25.5,
    carbs: 0,
    fat: 0.8,
    fiber: 0,
    sugar: 0,
    sodium: 333,
  },
  'beef mince': {
    name: 'Beef mince',
    baseQuantity: 100,
    baseUnit: 'gram',
    calories: 254,
    protein: 17.2,
    carbs: 0,
    fat: 20,
    fiber: 0,
    sugar: 0,
    sodium: 75,
  },
  salmon: {
    name: 'Salmon',
    baseQuantity: 100,
    baseUnit: 'gram',
    calories: 208,
    protein: 20,
    carbs: 0,
    fat: 13,
    fiber: 0,
    sugar: 0,
    sodium: 59,
  },
  vegetables: {
    name: 'Mixed vegetables',
    baseQuantity: 100,
    baseUnit: 'gram',
    calories: 55,
    protein: 2.8,
    carbs: 9,
    fat: 0.5,
    fiber: 3.6,
    sugar: 4.2,
    sodium: 45,
  },
  broccoli: {
    name: 'Broccoli',
    baseQuantity: 100,
    baseUnit: 'gram',
    calories: 34,
    protein: 2.8,
    carbs: 6.6,
    fat: 0.4,
    fiber: 2.6,
    sugar: 1.7,
    sodium: 33,
  },
  spinach: {
    name: 'Spinach',
    baseQuantity: 100,
    baseUnit: 'gram',
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    fiber: 2.2,
    sugar: 0.4,
    sodium: 79,
  },
  cucumber: {
    name: 'Cucumber',
    baseQuantity: 100,
    baseUnit: 'gram',
    calories: 15,
    protein: 0.7,
    carbs: 3.6,
    fat: 0.1,
    fiber: 0.5,
    sugar: 1.7,
    sodium: 2,
  },
  tomato: {
    name: 'Tomato',
    baseQuantity: 100,
    baseUnit: 'gram',
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    fiber: 1.2,
    sugar: 2.6,
    sodium: 5,
  },
  lettuce: {
    name: 'Lettuce',
    baseQuantity: 100,
    baseUnit: 'gram',
    calories: 15,
    protein: 1.4,
    carbs: 2.9,
    fat: 0.2,
    fiber: 1.3,
    sugar: 0.8,
    sodium: 28,
  },
  onion: {
    name: 'Onion',
    baseQuantity: 100,
    baseUnit: 'gram',
    calories: 40,
    protein: 1.1,
    carbs: 9.3,
    fat: 0.1,
    fiber: 1.7,
    sugar: 4.2,
    sodium: 4,
  },
  carrot: {
    name: 'Carrot',
    baseQuantity: 100,
    baseUnit: 'gram',
    calories: 41,
    protein: 0.9,
    carbs: 9.6,
    fat: 0.2,
    fiber: 2.8,
    sugar: 4.7,
    sodium: 69,
  },
  'bell pepper': {
    name: 'Bell pepper',
    baseQuantity: 100,
    baseUnit: 'gram',
    calories: 31,
    protein: 1,
    carbs: 6,
    fat: 0.3,
    fiber: 2.1,
    sugar: 4.2,
    sodium: 4,
  },
  beans: {
    name: 'Beans',
    baseQuantity: 100,
    baseUnit: 'gram',
    calories: 109,
    protein: 7,
    carbs: 19,
    fat: 0.5,
    fiber: 6.5,
    sugar: 0.3,
    sodium: 240,
  },
  lentils: {
    name: 'Lentils',
    baseQuantity: 100,
    baseUnit: 'gram',
    calories: 116,
    protein: 9,
    carbs: 20,
    fat: 0.4,
    fiber: 8,
    sugar: 1.8,
    sodium: 2,
  },
  chickpeas: {
    name: 'Chickpeas',
    baseQuantity: 100,
    baseUnit: 'gram',
    calories: 164,
    protein: 8.9,
    carbs: 27.4,
    fat: 2.6,
    fiber: 7.6,
    sugar: 4.8,
    sodium: 24,
  },
  'protein yogurt': {
    name: 'Protein yogurt',
    baseQuantity: 200,
    baseUnit: 'gram',
    calories: 148,
    protein: 20,
    carbs: 9,
    fat: 2.5,
    fiber: 0,
    sugar: 8,
    sodium: 82,
  },
  oats: {
    name: 'Oats',
    baseQuantity: 50,
    baseUnit: 'gram',
    calories: 194,
    protein: 6.8,
    carbs: 33,
    fat: 3.6,
    fiber: 5.3,
    sugar: 0.7,
    sodium: 3,
  },
  muesli: {
    name: 'Muesli',
    baseQuantity: 100,
    baseUnit: 'gram',
    calories: 372,
    protein: 10,
    carbs: 64,
    fat: 7,
    fiber: 7.5,
    sugar: 16,
    sodium: 12,
  },
  granola: {
    name: 'Granola',
    baseQuantity: 100,
    baseUnit: 'gram',
    calories: 451,
    protein: 10,
    carbs: 64,
    fat: 16,
    fiber: 8,
    sugar: 19,
    sodium: 120,
  },
  'whey protein': {
    name: 'Whey protein',
    baseQuantity: 30,
    baseUnit: 'gram',
    calories: 120,
    protein: 24,
    carbs: 2.5,
    fat: 1.8,
    fiber: 0,
    sugar: 1.8,
    sodium: 90,
  },
  egg: {
    name: 'Egg',
    baseQuantity: 1,
    baseUnit: 'piece',
    calories: 78,
    protein: 6.3,
    carbs: 0.6,
    fat: 5.3,
    fiber: 0,
    sugar: 0.6,
    sodium: 62,
  },
  avocado: {
    name: 'Avocado',
    baseQuantity: 50,
    baseUnit: 'gram',
    calories: 80,
    protein: 1,
    carbs: 4.2,
    fat: 7.4,
    fiber: 3.4,
    sugar: 0.2,
    sodium: 4,
  },
  almonds: {
    name: 'Almonds',
    baseQuantity: 30,
    baseUnit: 'gram',
    calories: 174,
    protein: 6.4,
    carbs: 6.5,
    fat: 15,
    fiber: 3.8,
    sugar: 1.3,
    sodium: 1,
  },
  walnuts: {
    name: 'Walnuts',
    baseQuantity: 30,
    baseUnit: 'gram',
    calories: 196,
    protein: 4.6,
    carbs: 4.1,
    fat: 19.6,
    fiber: 2,
    sugar: 0.8,
    sodium: 1,
  },
  cashews: {
    name: 'Cashews',
    baseQuantity: 30,
    baseUnit: 'gram',
    calories: 166,
    protein: 5.4,
    carbs: 9.1,
    fat: 13.2,
    fiber: 1,
    sugar: 1.8,
    sodium: 4,
  },
  pasta: {
    name: 'Pasta',
    baseQuantity: 100,
    baseUnit: 'gram',
    calories: 157,
    protein: 5.8,
    carbs: 30.9,
    fat: 0.9,
    fiber: 1.8,
    sugar: 0.6,
    sodium: 2,
  },
  pesto: {
    name: 'Pesto',
    baseQuantity: 30,
    baseUnit: 'gram',
    calories: 151,
    protein: 1.8,
    carbs: 2.4,
    fat: 15.3,
    fiber: 0.6,
    sugar: 1,
    sodium: 420,
  },
  wrap: {
    name: 'Wrap',
    baseQuantity: 1,
    baseUnit: 'piece',
    calories: 171,
    protein: 5.2,
    carbs: 28.5,
    fat: 4.8,
    fiber: 1.8,
    sugar: 1.7,
    sodium: 360,
  },
  'rice cakes': {
    name: 'Rice cakes',
    baseQuantity: 1,
    baseUnit: 'piece',
    calories: 35,
    protein: 0.7,
    carbs: 7.3,
    fat: 0.3,
    fiber: 0.3,
    sugar: 0.1,
    sodium: 30,
  },
  crackers: {
    name: 'Crackers',
    baseQuantity: 1,
    baseUnit: 'piece',
    calories: 42,
    protein: 1.2,
    carbs: 7,
    fat: 1.1,
    fiber: 0.6,
    sugar: 0.3,
    sodium: 75,
  },
  cheese: {
    name: 'Cheese',
    baseQuantity: 100,
    baseUnit: 'gram',
    calories: 356,
    protein: 25,
    carbs: 2.2,
    fat: 27,
    fiber: 0,
    sugar: 0.5,
    sodium: 819,
  },
  butter: {
    name: 'Butter',
    baseQuantity: 10,
    baseUnit: 'gram',
    calories: 72,
    protein: 0.1,
    carbs: 0.1,
    fat: 8.1,
    fiber: 0,
    sugar: 0.1,
    sodium: 72,
  },
  'protein bar': {
    name: 'Protein bar',
    baseQuantity: 1,
    baseUnit: 'piece',
    calories: 198,
    protein: 20,
    carbs: 18,
    fat: 7,
    fiber: 6,
    sugar: 2.5,
    sodium: 180,
  },
  'pasta sauce': {
    name: 'Pasta sauce',
    baseQuantity: 100,
    baseUnit: 'gram',
    calories: 68,
    protein: 1.8,
    carbs: 8.7,
    fat: 2.8,
    fiber: 1.7,
    sugar: 6.2,
    sodium: 360,
  },
  dressing: {
    name: 'Dressing',
    baseQuantity: 25,
    baseUnit: 'ml',
    calories: 110,
    protein: 0.3,
    carbs: 3.5,
    fat: 10,
    fiber: 0,
    sugar: 2.5,
    sodium: 260,
  },
  'olive oil': {
    name: 'Olive oil',
    baseQuantity: 10,
    baseUnit: 'ml',
    calories: 88,
    protein: 0,
    carbs: 0,
    fat: 10,
    fiber: 0,
    sugar: 0,
    sodium: 0,
  },
  liverwurst: {
    name: 'Liverwurst',
    baseQuantity: 100,
    baseUnit: 'gram',
    calories: 290,
    protein: 14,
    carbs: 3,
    fat: 25,
    fiber: 0,
    sugar: 0.8,
    sodium: 980,
  },
  stroopwafel: {
    name: 'Stroopwafel',
    baseQuantity: 1,
    baseUnit: 'piece',
    calories: 150,
    protein: 1.5,
    carbs: 20,
    fat: 7,
    fiber: 0.4,
    sugar: 11,
    sodium: 95,
  },
};
