import type { NutritionReference } from '@/types/nutrition';

export const mockNutritionDatabase: Record<string, NutritionReference> = {
  bread: {
    name: 'Bread',
    baseQuantity: 1,
    baseUnit: 'slice',
    calories: 82,
    protein: 3.2,
    carbs: 14.4,
    fat: 1.1,
    fiber: 2,
    sugar: 1.6,
    sodium: 145,
  },
  'peanut butter': {
    name: 'Peanut butter',
    baseQuantity: 15,
    baseUnit: 'gram',
    calories: 89,
    protein: 3.8,
    carbs: 3.2,
    fat: 7.5,
    fiber: 1.2,
    sugar: 1.4,
    sodium: 72,
  },
  'semi-skimmed milk': {
    name: 'Semi-skimmed milk',
    baseQuantity: 100,
    baseUnit: 'ml',
    calories: 46,
    protein: 3.4,
    carbs: 4.9,
    fat: 1.5,
    fiber: 0,
    sugar: 4.9,
    sodium: 44,
  },
  'chicken sandwich': {
    name: 'Chicken sandwich',
    baseQuantity: 1,
    baseUnit: 'serving',
    calories: 365,
    protein: 30,
    carbs: 33,
    fat: 11,
    fiber: 4,
    sugar: 5,
    sodium: 620,
  },
  apple: {
    name: 'Apple',
    baseQuantity: 1,
    baseUnit: 'piece',
    calories: 95,
    protein: 0.5,
    carbs: 25,
    fat: 0.3,
    fiber: 4.4,
    sugar: 19,
    sodium: 2,
  },
  banana: {
    name: 'Banana',
    baseQuantity: 1,
    baseUnit: 'piece',
    calories: 105,
    protein: 1.3,
    carbs: 27,
    fat: 0.4,
    fiber: 3.1,
    sugar: 14,
    sodium: 1,
  },
  rice: {
    name: 'Rice',
    baseQuantity: 100,
    baseUnit: 'gram',
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
    fiber: 0.4,
    sugar: 0.1,
    sodium: 1,
  },
  salmon: {
    name: 'Salmon',
    baseQuantity: 100,
    baseUnit: 'gram',
    calories: 208,
    protein: 20,
    carbs: 0,
    fat: 13,
    fiber: 0,
    sugar: 0,
    sodium: 59,
  },
  vegetables: {
    name: 'Mixed vegetables',
    baseQuantity: 100,
    baseUnit: 'gram',
    calories: 55,
    protein: 2.8,
    carbs: 9,
    fat: 0.5,
    fiber: 3.6,
    sugar: 4.2,
    sodium: 45,
  },
  'protein yogurt': {
    name: 'Protein yogurt',
    baseQuantity: 200,
    baseUnit: 'gram',
    calories: 148,
    protein: 20,
    carbs: 9,
    fat: 2.5,
    fiber: 0,
    sugar: 8,
    sodium: 82,
  },
  oats: {
    name: 'Oats',
    baseQuantity: 50,
    baseUnit: 'gram',
    calories: 194,
    protein: 6.8,
    carbs: 33,
    fat: 3.6,
    fiber: 5.3,
    sugar: 0.7,
    sodium: 3,
  },
  egg: {
    name: 'Egg',
    baseQuantity: 1,
    baseUnit: 'piece',
    calories: 78,
    protein: 6.3,
    carbs: 0.6,
    fat: 5.3,
    fiber: 0,
    sugar: 0.6,
    sodium: 62,
  },
  avocado: {
    name: 'Avocado',
    baseQuantity: 50,
    baseUnit: 'gram',
    calories: 80,
    protein: 1,
    carbs: 4.2,
    fat: 7.4,
    fiber: 3.4,
    sugar: 0.2,
    sodium: 4,
  },
  pasta: {
    name: 'Pasta',
    baseQuantity: 100,
    baseUnit: 'gram',
    calories: 157,
    protein: 5.8,
    carbs: 30.9,
    fat: 0.9,
    fiber: 1.8,
    sugar: 0.6,
    sodium: 2,
  },
  'olive oil': {
    name: 'Olive oil',
    baseQuantity: 10,
    baseUnit: 'ml',
    calories: 88,
    protein: 0,
    carbs: 0,
    fat: 10,
    fiber: 0,
    sugar: 0,
    sodium: 0,
  },
  liverwurst: {
    name: 'Liverwurst',
    baseQuantity: 100,
    baseUnit: 'gram',
    calories: 290,
    protein: 14,
    carbs: 3,
    fat: 25,
    fiber: 0,
    sugar: 0.8,
    sodium: 980,
  },
  stroopwafel: {
    name: 'Stroopwafel',
    baseQuantity: 1,
    baseUnit: 'piece',
    calories: 150,
    protein: 1.5,
    carbs: 20,
    fat: 7,
    fiber: 0.4,
    sugar: 11,
    sodium: 95,
  },
};
